let highScore=[0]; //for tracking highest score of one session
let gameSeq=[]; // for tracking the sequence in which the game flashes btns
let userSeq=[]; //for tracking the sequence of users btn flashes

let btns=["orange","green","red","purple"]; // for generating random indexes so that random button flashes
let started=false; //before game starts
let level=0; //to track level 

let h3=document.querySelector("h3"); //display message to user
let startbtn=document.querySelector("#start");

document.addEventListener("keydown",function(){ //game starts
    if(started==false)
    {
        started=true;
        levelup(); //level 1 begins
    }
});
startbtn.addEventListener("click",function(){ //for mobile devices 
    if(started==false)
    {
        started=true;
        startbtn.style.display= "none"; //making the start button invisible as the game starts
        h3.style.display="inline-block";
        levelup(); //level 1 begins
    }
});

function gameflash(btn) // to flash the btn chosen by the game
{
    btn.classList.add("flash");
    setTimeout(function(){
        btn.classList.remove("flash");
    },250)
}
function userflash(btn) // to flash btn chosen by user
{
    btn.classList.add("flash");
    setTimeout(function(){
        btn.classList.remove("flash");
    },250)
}

function levelup(){
    userSeq=[];// so that the user has to click the entire sequence
    level++;
    h3.innerText=`Level ${level}` //display level no.

    let randIdx=Math.floor(Math.random() * 3); //random btn choose
    let randColor= btns[randIdx]; //using array of colors to get the color of btn chosen
    let randBtn= document.querySelector(`.${randColor}`); //to get the specific btn
    gameSeq.push(randColor); //adding btn chosen to sequenece for tracking
    gameflash(randBtn); 
}

function checkAns(idx){ //matches the btn clicked by user 
    if(userSeq[idx]===gameSeq[idx]){ //checking if the last clicked button is same as generated by game
    if(userSeq.length==gameSeq.length)//checking if the user has clicked the same no. of buttons as generated by game
        {
           setTimeout(levelup,1000); //level up takes to next level and new btn is flashed
        }
    }
    else{
        if(highScore[0]< level-1) //compares score to highscore
        {
            highScore[0]=level-1;     

        }
        console.log(highScore);
    h3.innerHTML=`Game Over! Your score was <b>${level-1}<b>.<br>Highest score for this session:${highScore[0]} <br> Restart Game.`;
    
    document.querySelector("body").style.backgroundColor="red"; // when game over body turns red
    setTimeout(function(){
    document.querySelector("body").style.backgroundColor="white";
    },150);
    reset();
    }
}
function btnpress(){ //tracks the btn clicked by user and adds that to usersequence for checking 
  let btn=this; //btn now stores the button that was clicked
  userflash(btn);

  let userColor=btn.getAttribute("id");
  userSeq.push(userColor);

  checkAns(userSeq.length-1); //for matching
}

let allBtns=document.querySelectorAll(".btn"); //adding event listener to all the btns
for (btn of allBtns){
    btn.addEventListener("click", btnpress); // when the user clicks btn on screen
}

function reset() // to reset the game
{
    started=false;
    level=0
    gameSeq=[];
    userSeq=[];
    if(window.innerWidth<=768) //button would appear on devices;
    {
    startbtn.style.display="inline-block";
    }
    
}
 
